tradingstrategy-ai/web3-ethereum-defi

eth_defi/token_tax.py
eth_defi/uniswap_v2/token_tax.py
eth_defi/utils.py
tests/test_token_tax.py

Merging token tax functionality

Token tax 5

---

CHANGELOG.md
eth_defi/revert_reason.py
eth_defi/uniswap_v2/fees.py
eth_defi/uniswap_v2/swap.py
tests/test_uniswap_v2_price.py
tests/test_uniswap_v2_swap.py

Support three-way swap

---

CHANGELOG.md
docs/source/index.rst
eth_defi/event_reader/conversion.py
eth_defi/event_reader/logresult.py
eth_defi/event_reader/reader.py
eth_defi/event_reader/web3factory.py
eth_defi/event_reader/web3worker.py
eth_defi/middleware.py
poetry.lock
pyproject.toml
scripts/read-uniswap-v2-pairs-and-swaps-concurrent.py
scripts/read-uniswap-v2-pairs-and-swaps.py
tests/test_block_reader.py

- Concurrent read of events 
- Add middleware to handle web3 retries

Thread pool worker implementation

---

CHANGELOG.md
eth_defi/uniswap_v2/fees.py
poetry.lock
pyproject.toml
tests/uniswap_v2/test_uniswap_v2_price.py
tests/uniswap_v2/test_uniswap_v2_swap.py

Match slippage calculation with [official Uniswap V2 SDK](https://github.com/Uniswap/v2-sdk)
Also created new unit tests with exact same inputs as the SDK to confirm we have right calculation.

Fix slippage calculation in Uniswap V2

---

CHANGELOG.md
docs/source/api/index.rst
eth_defi/price_oracle/oracle.py
eth_defi/uniswap_v2/oracle.py
eth_defi/uniswap_v3/oracle.py
tests/uniswap_v3/test_uniswap_v3_oracle.py

Add price oracle support for Uniswap V3, allow updating price both in single thread and concurrently

Uniswap v3 price oracle

---

CHANGELOG.md
eth_defi/uniswap_v3/oracle.py
scripts/pancakeswap-live-price.py
scripts/uniswap-v3-live-price.py

* Add `update_live_price_feed` for uniswap v3
* Add a live price test script

Support uniswap v3 live price

---

.gitignore
Makefile
contracts/aave-v3/.gitignore
contracts/aave-v3/README.md
contracts/aave-v3/package-lock.json
contracts/aave-v3/package.json
docs/source/tutorials/aave-v3-interest-analysis.ipynb
eth_defi/aave_v3/README.md
eth_defi/aave_v3/balances.py
eth_defi/aave_v3/constants.py
eth_defi/aave_v3/events.py
eth_defi/aave_v3/rates.py
eth_defi/uniswap_v3/events.py

This PR includes Aave v3 constants, event reading from blockchain and a Jupyter notebook for analyzing the data, and event documentation in eth_defi/aave_v3/README.md.
The Aave v3 ABI JSON files can be generated with `make aavev3`, which copies them from the @aave/core-v3 NPM package to the working directory (Node.js required).

Initial version of Aave v3 integration (issue #5)

---

.github/workflows/test.yml
CHANGELOG.md
README.md
docs/source/index.rst
docs/source/troubleshooting.rst
eth_defi/uniswap_v2/deployment.py
scripts/bnb-chain-get-logs-test.py
scripts/trader-joe-test.py
tests/test_price_oracle.py

Adding Trader Joe compatibility

---

CHANGELOG.md
eth_defi/event_reader/conversion.py
eth_defi/event_reader/reader.py
eth_defi/event_reader/web3factory.py
eth_defi/price_oracle/oracle.py
eth_defi/uniswap_v2/pair.py
eth_defi/uniswap_v2/synthetic_data.py
eth_defi/utils.py
scripts/read-uniswap-v2-pairs-and-swaps.py
tests/uniswap_v2/test_uniswap_v2_swap.py
tests/uniswap_v2/test_uniswap_v2_synthetic.py

- Fix small papercuts in API design

Reader fixes

---

CHANGELOG.md
eth_defi/chain.py
eth_defi/event_reader/block_data_store.py
eth_defi/event_reader/block_header.py
eth_defi/event_reader/block_time.py
eth_defi/event_reader/filter.py
eth_defi/event_reader/parquet_block_data_store.py
eth_defi/event_reader/reader.py
eth_defi/event_reader/web3factory.py
eth_defi/uniswap_v2/pair.py
tests/test_ganache.py
tests/test_measure_block_time.py
tests/test_token_tax.py

- Multicontract filtering for the event reader
- Multiple new APIs

Better API and document Filter in event reader better

---

eth_defi/uniswap_v3/deployment.py
eth_defi/uniswap_v3/swap.py
eth_defi/uniswap_v3/utils.py
poetry.lock
pyproject.toml
tests/uniswap_v3/test_uniswap_v3_swap.py

Uniswap v3 swap support

---

CHANGELOG.md
eth_defi/event_reader/reader.py
pyproject.toml
tests/test_block_reader.py
tests/test_event_reader.py

- Check for the returned timestamp values for potential error

Add coverage and interface checks for bad timestamp provider

---

CHANGELOG.md
eth_defi/middleware.py
tests/test_middleware.py

- Include HTTP status code matching
- Better tests and API documentation

More config and docs for the retry middleware

---

CHANGELOG.md
eth_defi/event_reader/reader.py
eth_defi/middleware.py

- [Fix sleep timer not reset between different function calls](https://github.com/tradingstrategy-ai/web3-ethereum-defi/commit/e946913e6e59d7fc8fa9cd1ae01d3ce5330ed804)

Fix retry sleep

---

CHANGELOG.md
docs/source/conf.py
eth_defi/uniswap_v3/price.py
eth_defi/uniswap_v3/utils.py
scripts/bnb-chain-get-logs-test.py
scripts/uniswap-v2-pairs-and-swaps.py
scripts/uniswap-v2-swaps-live.py
tests/uniswap_v3/test_uniswap_v3_utils.py

- add decode_path method for Uniswap V3 + testing
- update CHANGELOG.md to `0.13.11`
Some files were changed due to black formatting. Real changes are in `eth_defi/uniswap_v3/price.py`, `eth_defi/uniswap_v3/utils.py`, and `tests/uniswap_v3/test_uniswap_v3_utils.py`

Uni v3 testing

---

.github/workflows/test.yml
eth_defi/anvil.py
eth_defi/ganache.py
eth_defi/uniswap_v2/token_tax.py
eth_defi/utils.py
tests/test_anvil.py
tests/test_token_tax.py

- Replace Anvil as the solution for mainnet forks
- This is due to Ganache internal instability
- Start the process to remove Ganache from the codebase where it is not needed

Anvil over ganache

---

CHANGELOG.md
docs/source/api/index.rst
eth_defi/anvil.py
eth_defi/uniswap_v3/utils.py
eth_defi/utils.py
tests/manual_bnb_chain_build_transaction.py
tests/test_anvil.py
tests/test_confirmation.py
tests/test_decode_tx.py
tests/test_gas.py
tests/test_revert_reason.py
tests/uniswap_v2/test_uniswap_v2_price.py
tests/uniswap_v2/test_uniswap_v2_swap.py
tests/uniswap_v3/test_uniswap_v3_utils.py

- make `test_revert_reason` Anvil based

Update tests to anvil

---

CHANGELOG.md
eth_defi/trade.py
eth_defi/uniswap_v2/analysis.py
eth_defi/uniswap_v3/analysis.py
eth_defi/uniswap_v3/deployment.py
tests/uniswap_v3/test_uniswap_v3_analysis.py

- Adds `uniswap_v3.analysis`. Similar to `uniswap_v2.analysis`, but tailored to Uniswap V3
- Also adds `mock_partial_deployment` for Uniswap V3, following V2

add uniswap v3 analysis

---

CHANGELOG.md
eth_defi/event.py
eth_defi/event_reader/filter.py
eth_defi/event_reader/logresult.py
eth_defi/event_reader/reader.py
eth_defi/revert_reason.py
eth_defi/uniswap_v2/analysis.py
eth_defi/uniswap_v2/deployment.py
eth_defi/uniswap_v2/liquidity.py
eth_defi/uniswap_v2/utils.py
eth_defi/uniswap_v3/analysis.py
eth_defi/uniswap_v3/deployment.py
eth_defi/uniswap_v3/utils.py
poetry.lock
pyproject.toml
tests/uniswap_v3/test_uniswap_v3_pool.py

- Switch from Web3.py 5.x to Web3.py 6.x 
- Various API compatibility breakage

Web3 6.0+ migration

---

CHANGELOG.md
eth_defi/chain.py
eth_defi/event_reader/web3factory.py
eth_defi/middleware.py
scripts/verify-node-integrity.py
tests/test_middleware.py

- Add API call count middleware
- Fix: Clean accidentally released breakpoint code in revert middleware

Adding API call count middlware

---

eth_defi/anvil.py
eth_defi/chainlink/round_data.py
eth_defi/enzyme/deployment.py
eth_defi/enzyme/generic_adapter.py
eth_defi/enzyme/price_feed.py
eth_defi/enzyme/vault.py
eth_defi/enzyme/vault_controlled_wallet.py
eth_defi/event_reader/multithread.py
eth_defi/event_reader/reader.py
eth_defi/hotwallet.py
eth_defi/revert_reason.py
eth_defi/trace.py
pyproject.toml
scripts/enzyme/fetch-price-feeds.py
scripts/multithread-reader.py
tests/enzyme/test_enzyme_deploy.py
tests/enzyme/test_generic_adapter.py
tests/enzyme/test_polygon.py
tests/enzyme/test_price_feed.py
tests/enzyme/test_vault_controlled_wallet.py
tests/test_trace.py

- Create an Ethereum wallet signing like interface that delegates transactions to Enzyme Vault's GenericAdapter

Vault controlled wallet

---

.github/workflows/test.yml
CHANGELOG.md
eth_defi/chain.py
eth_defi/enzyme/deployment.py
eth_defi/enzyme/price_feed.py
eth_defi/enzyme/vault.py
eth_defi/event_reader/multithread.py
eth_defi/event_reader/progress_update.py
eth_defi/token.py
poetry.lock
pyproject.toml
scripts/enzyme/fetch-supported-tokens.py
tests/enzyme/test_price_feed.py
tests/test_price_oracle.py
tests/test_token_tax.py

- Support Enzyme's feed removal
- Various bug fixes - see CHANGELOG

Enzyme remove feeds

---

eth_defi/gas.py

fixes [#32](https://github.com/tradingstrategy-ai/trade-executor/issues/323)

gas fix for polygon

---

docs/source/api/aave_v3/index.rst
eth_defi/aave_v3/loan.py
tests/test_aave_deposit.py

Added `eth_defi.aave_v3.loan` module that contains : 
- `approve_token()` function
- `deposit_in_aave()` function
Added `tests.test_aave_deposit.py` that contains 3 tests :
- `test_anvil_output()`
- `test_anvil_forked_chain_id()`
- `test_anvil_fork_deposit_aave()`
Black formatted :
- `eth_defi.aave_v3.loan`
- `tests.test_aave_deposit.py`
Updated `docs/source/api/aave_v3/index.rst`

Aave deposit

---

.github/workflows/test.yml

Use Github Action https://github.com/foundry-rs/foundry-toolchain instead of manually install Foundry

Fix install Foundry

---

eth_defi/abi.py
eth_defi/enzyme/deployment.py
eth_defi/enzyme/utils.py
eth_defi/uniswap_v3/deployment.py
tests/aave_v3/test_aave_v3_loan.py
tests/aave_v3/test_aave_v3_short.py
tests/enzyme/test_vault_controlled_wallet.py
tests/uniswap_v3/test_uniswap_v3_deployment.py
tests/uniswap_v3/test_uniswap_v3_pool.py

Add tests and script to demo how to open and close short position with Aave v3
Close #110

Aave v3 short

---

CHANGELOG.md
eth_defi/enzyme/events.py
eth_defi/token.py
eth_defi/usdc/eip_3009.py
tests/enzyme/test_events.py

- Add `fetch_vault_balances()`

Enzyme live balances

---

eth_defi/uniswap_v3/price.py
tests/uniswap_v3/test_uniswap_v3_price.py

Add verbose info to uniswap v3 price estimator

---

CHANGELOG.md
eth_defi/uniswap_v3/pool.py
eth_defi/uniswap_v3/price.py
tests/uniswap_v3/test_uniswap_v3_price.py

Part of #135 
Add an util function to get onchain price of Uniswap v3 pool

Get onchain price of Uniswap v3 pool

---

CHANGELOG.md
eth_defi/aave_v3/deployer.py
eth_defi/aave_v3/events.py
eth_defi/aave_v3/reserve.py
eth_defi/chain.py
eth_defi/trade.py
eth_defi/uniswap_v2/analysis.py
eth_defi/uniswap_v3/analysis.py
tests/aave_v3/test_aave_v3_reserve_data.py

- Add: Aave v3 reserve data queries

Aave reserves data

---

CHANGELOG.md
eth_defi/middleware.py
eth_defi/provider/broken_provider.py
eth_defi/uniswap_v3/swap.py
pyproject.toml
tests/test_chain.py

- Asking data for the latest block crashes on Ankr

Unstable blockchain chain tip fixes for Ankr

---

CHANGELOG.md
eth_defi/confirmation.py
eth_defi/event_reader/lazy_timestamp_reader.py
eth_defi/hotwallet.py
eth_defi/provider/fallback.py
tests/rpc/test_fallback_provider.py

- Attempt to broadcast transactions using multiple nodes
- Handle cases where a node fails to broadcast/confirm transaction

Broadcast txs using multiple nodes

---

CHANGELOG.md
eth_defi/confirmation.py

- Raise the last exception from the last provider if all providers fail
- Better logging on which providers success and which fail

Better exc handling when broadcasting with many providers

---

CHANGELOG.md
eth_defi/one_delta/position.py
tests/one_delta/conftest.py
tests/one_delta/test_one_delta_short_multipair.py
tests/one_delta/test_one_delta_short_single_pair.py
tests/one_delta/utils.py

Improve close short position to be able to close and withdraw for multiple positions

1delta close short improvement

---

CHANGELOG.md
docs/source/api/core/index.rst
eth_defi/confirmation.py
eth_defi/middleware.py
eth_defi/provider/anvil.py
eth_defi/provider/fallback.py
eth_defi/timestamp.py
eth_defi/utils.py
pyproject.toml

- Figure out Anvil unreliablility issues and how to tackle them
- Add `eth_defi.timestamp` with helpers (lifted from trade-executor)

Anvil mine fixes

---

eth_defi/one_delta/position.py
eth_defi/one_delta/utils.py
tests/one_delta/test_one_delta_short_single_pair.py

* Increase short position
* Reduce short position using exact input or output
Part of https://github.com/tradingstrategy-ai/trade-executor/issues/713

1delta modify short position size

---

eth_defi/one_delta/deployment.py
eth_defi/one_delta/price.py
eth_defi/one_delta/utils.py
eth_defi/uniswap_v3/price.py
tests/one_delta/conftest.py
tests/one_delta/test_one_delta_price.py
tests/rpc/test_anvil.py
tests/rpc/test_ganache.py

Integrate 1delta quoter to estimate amount in / out
Part of https://github.com/tradingstrategy-ai/trade-executor/issues/739

1delta price helper

---

.github/workflows/test.yml
CHANGELOG.md
contracts/guard/README.md
contracts/guard/foundry.toml
docs/source/tutorials/enzyme-deploy.rst
eth_defi/abi.py
eth_defi/deploy.py
eth_defi/enzyme/deployment.py
eth_defi/enzyme/generic_adapter_vault.py
eth_defi/enzyme/vault.py
eth_defi/etherscan/__init__.py
eth_defi/etherscan/verify.py
eth_defi/foundry/__init__.py
eth_defi/foundry/forge.py
eth_defi/hotwallet.py
eth_defi/provider/anvil.py
eth_defi/trace.py
poetry.lock
pyproject.toml
scripts/enzyme/deploy-vault.py
tests/enzyme/test_guard_enzyme_uniswap_v2.py
tests/enzyme/test_guard_enzyme_uniswap_v3.py
tests/rpc/test_forge_deploy.py
tests/test_reorganisation_monitor_polygon.py

- Create `deploy_contract_with_forge` to be able to do Etherscan verified deployments
- Convert Enzyme vault deployment toolchain to use `deploy_contract_with_forge`
- Add some quality of life improvements to APIs

More enzyme deployment

---

eth_defi/enzyme/vault.py
tests/enzyme/test_guard_enzyme_uniswap_v2.py

- Export `termsOfService` contract as the part of Vault data structure

Export TermsOfService contract in Vault data structure

---

CHANGELOG.md
contracts/in-house/README.md
contracts/in-house/src/AdapterBase_flatten.sol
contracts/in-house/src/GuardedGenericAdapter.sol
contracts/in-house/src/IEIP3009.sol
contracts/in-house/src/IERC20.sol
contracts/in-house/src/VaultSpecificGenericAdapter.sol
pyproject.toml

- References to Enzyme contracts make deploying contracts very difficult, as building enzyme contracts needs a broken and brittle Hardhat toolchain

Root out enzyme

---

.github/workflows/test.yml
tests/aave_v3/test_aave_v3_loan.py
tests/enzyme/test_price_feed.py
tests/enzyme/test_vault_controlled_wallet.py
tests/guard/test_guard_simple_vault_uniswap_v2.py

Make sure test suite is compatible with both old and newer Foundry versions

Newer foundry compatibility

---

docs/source/tutorials/index.rst
docs/source/tutorials/uniswap-v3-price-impact.rst
eth_defi/uniswap_v3/pool.py
eth_defi/uniswap_v3/price.py
scripts/uniswap-v3-price-impact.py
tests/enzyme/test_arbitrum_trade.py

- [Add a tutorial for Uniswap v3 price impact estimation](https://web3-ethereum-defi.readthedocs.io/tutorials/)

Add price impact example

---

CHANGELOG.md
eth_defi/confirmation.py
eth_defi/provider/mev_blocker.py
eth_defi/uniswap_v3/analysis.py
tests/rpc/test_mev_blocker.py

- MEVBlocker.io does not work with multi tx broadcasts

Mev blocker broadcast

---

.gitmodules
scripts/velvet/rebalance-tx.py

- Another attempt to include Velvet Capital contracts

Velvet attempt two

---

eth_defi/balances.py
eth_defi/provider/anvil.py
eth_defi/velvet/__init__.py
eth_defi/velvet/config.py
eth_defi/velvet/deposit.py
eth_defi/velvet/enso.py
tests/velvet/test_velvet_api.py

- Adding more vault interface structure
- Optimise `fetch_erc20_details` caching in some use cases

Generic vault interface, second batch of work

---

CHANGELOG.md
eth_defi/balances.py
eth_defi/hotwallet.py
eth_defi/velvet/__init__.py
eth_defi/velvet/deposit.py
tests/velvet/test_velvet_api.py

- Add more of Velvet API
- Deposit is only manually testable

Add deposit test function

---

docs/source/api/vault/index.rst
eth_defi/balances.py
eth_defi/lagoon/valuation_commitee.py
eth_defi/lagoon/vault.py
eth_defi/token.py
eth_defi/vault/base.py
eth_defi/vault/valuation.py
tests/lagoon/conftest.py
tests/lagoon/test_lagoon_valuation.py

- Add pure onchain data source-based portfolio valuation, in the preparation for valuation committee hooks
- Clean up documentation regarding vaults

Start Lagoon valuation work

---

eth_defi/lagoon/valuation_commitee.py
eth_defi/lagoon/vault.py
eth_defi/safe/trace.py
eth_defi/trace.py
eth_defi/vault/base.py
eth_defi/velvet/__init__.py
tests/lagoon/conftest.py
tests/lagoon/test_lagoon_info.py
tests/lagoon/test_lagoon_swap.py
tests/lagoon/test_lagoon_valuation.py
tests/one_delta/test_one_delta_short_single_pair.py

- Add better vault core info handling
- Add share and denomination token handling
- Add valuation manager to update the vault valution

Lagoon updates

---

tests/velvet/test_velvet_api.py

- More work regarding vault integration

More vault integration work

---

eth_defi/lagoon/vault.py
eth_defi/provider/multi_provider.py
eth_defi/safe/trace.py
eth_defi/vault/base.py
tests/lagoon/test_lagoon_swap.py
tests/lagoon/test_lagoon_valuation.py
tests/one_delta/test_one_delta_short_multipair.py
tests/velvet/test_velvet_api.py

- Work around broken `execTransactionFromModule` gas estimation
- Add `LagoonFlowManager`
- Add `FlowManager.fetch_pending_redemption()`

Added pending redemptions number

---

docs/source/api/velvet/index.rst
eth_defi/trade.py
eth_defi/uniswap_v2/pair.py
eth_defi/velvet/analysis.py
eth_defi/velvet/config.py
eth_defi/velvet/deposit.py
eth_defi/velvet/enso.py
eth_defi/velvet/vault.py
tests/lagoon/test_lagoon_valuation.py
tests/velvet/test_velvet_api.py

- Add `analyse_trade_by_receipt_generic()`
- Fix bunch of Velvet brokenness issues

Enso price analysis

---

eth_defi/token.py
eth_defi/velvet/vault.py
tests/velvet/test_velvet_api.py

- When `swap_all` flag is set, check that the amount matches the onchain amount exactly

Try to avoid any rounding issues when swapping all tokens with Velvet and Enso

---

.github/workflows/test.yml
CHANGELOG.md
contracts/guard/foundry.toml
eth_defi/foundry/forge.py
eth_defi/lagoon/deployment.py
eth_defi/provider/anvil.py

- Because older version had issues on getting installed on Github CI

Upgrade to Anvil 0.3

---

eth_defi/foundry/forge.py
eth_defi/lagoon/deployment.py

- Add contract verification support for Lagoon contract deployments

Deploy lagoon with forge

---

docs/source/api/lagoon/index.rst
eth_defi/lagoon/beacon_proxy.py
eth_defi/lagoon/deployment.py

- Add: `deploy_beacon_proxy()`

Lagoon beacon deployment

---

tests/aave_v3/test_aave_v3_loan.py
tests/lagoon/conftest.py
tests/lagoon/test_lagoon_uniswap_v3.py
tests/lagoon/test_lagoon_valuation.py

- Fix Lagoon tests that are damaged by the latest changes
- Some Aave tests are disabled until a proper fix is in place

Merge fixes for Lagoon

---

eth_defi/gmx/plans.md

added draft for GMX integration

chore: Created plans.md

---

pyproject.toml

feat: CLeaned up dev dep gorups

---

eth_defi/token.py
eth_defi/trade.py
eth_defi/uniswap_v2/analysis.py
tests/uniswap_v2/test_uniswap_v2_analysis.py
tests/uniswap_v2/test_uniswap_v2_analysis_token_tax.py

- Add support for `eth_defi.uniswap_v2.analysis.analyse_trade_by_hash` for token swap where the token is taxd

Analyse token tax trade

---

eth_defi/erc_4626/analysis.py
eth_defi/erc_4626/core.py
eth_defi/erc_4626/estimate.py
eth_defi/erc_4626/flow.py
eth_defi/erc_4626/vault.py
eth_defi/event_reader/multicall_batcher.py
tests/ipor/test_ipor_deposit.py
tests/test_event_reader.py
tests/velvet/test_velvet_bnb_intent.py

- Updates for ERC-4626 deposit/redemption handling

Vault updates

---

eth_defi/erc_4626/analysis.py
eth_defi/erc_4626/core.py
eth_defi/erc_4626/estimate.py
eth_defi/erc_4626/flow.py
eth_defi/erc_4626/vault.py
eth_defi/event_reader/multicall_batcher.py
eth_defi/gas.py
tests/ipor/test_ipor_deposit.py
tests/test_event_reader.py
tests/velvet/test_velvet_bnb_intent.py

- Small fixes here and there for ERC-4626 vault handling

Vault updates and fixes

---

docs/source/api/provider/index.rst
docs/source/troubleshooting.rst
docs/source/tutorials/chainlink-native-token.rst
docs/source/tutorials/chainlink-price-feed.rst
docs/source/tutorials/erc-4626-deposit-redeem.rst
docs/source/tutorials/erc-4626-historical-apy.rst
docs/source/tutorials/erc-4626-read-apy.rst
docs/source/tutorials/erc-4626-scan-prices.rst
docs/source/tutorials/erc-4626-scan-vaults.rst
docs/source/tutorials/gmx-swap.rst
docs/source/tutorials/index.rst
docs/source/tutorials/live-price.rst
docs/source/tutorials/live-swap-minimal.rst
docs/source/tutorials/make-uniswap-v3-swap-in-python.rst
docs/source/tutorials/mev-blocker.rst
docs/source/tutorials/multicall3-with-python.rst
docs/source/tutorials/multithread-reader.rst
docs/source/tutorials/pancakeswap-live-minimal.rst
docs/source/tutorials/transfer.rst
docs/source/tutorials/uniswap-v3-price-impact.rst
docs/source/tutorials/uniswap-v3-price-simple.rst
docs/source/tutorials/verify-node-integrity.rst
eth_defi/provider/anvil.py
eth_defi/provider/env.py
eth_defi/token.py
eth_defi/trace.py
eth_defi/utils.py
eth_defi/vault/base.py
scripts/erc-4626/erc-4626-deposit-redeem.py

- Add example tutorial to test ERC-4626 vault deposits and redemptions
- Improve developer experience of Anvil mainnet forking
- Fix some docs legacy issues

ERC-4626 Vault deposit example

---

eth_defi/provider/fallback.py

Fix issue with ExtraValueError

Change ExtraValueError

---

eth_defi/chain.py
eth_defi/event_reader/reader.py
eth_defi/timestamp.py

- Timezone info was injected in somewhere, somehow

Try to make sure all timestamps are timezone-naive

---

eth_defi/hypersync/server.py
scripts/hypersync/hacked-eip-1967-proxy-scanner.py

- Detect potentially compromised EIP-1967 upgrade proxies through all chains supported by HyperSync
- See Twitter thread: https://x.com/moo9000/status/1958473690997236025

Add EIP-1967 breached proxy scanner

---

docs/source/conf.py
eth_defi/erc_4626/classification.py
eth_defi/erc_4626/deposit_redeem.py
eth_defi/erc_4626/estimate.py
eth_defi/lagoon/deposit_redeem.py
eth_defi/lagoon/vault.py
eth_defi/vault/base.py
eth_defi/vault/deposit_redeem.py
tests/erc_4626/test_4626_deposit_redeem.py
tests/gains/test_gtrade_usdc.py
tests/lagoon/test_erc_7540_deposit_redeem.py
tests/test_event_reader.py

Adding vault deposit/redeem estimate

---

docs/source/api/hypersync/index.rst
eth_defi/erc_4626/hypersync_discovery.py
eth_defi/event_reader/block_header.py
eth_defi/hypersync/server.py
eth_defi/hypersync/timestamp.py
eth_defi/utils.py
tests/hypersync/test_hypersync_block_timestamp.py

- Add `get_block_timestamps_using_hypersync()`

Fetch timestamps using Hypersync

---

eth_defi/erc_4626/lead_scan_core.py
eth_defi/research/vault_metrics.py
eth_defi/research/wrangle_vault_prices.py
eth_defi/vault/vaultdb.py
scripts/erc-4626/clean-prices.py
scripts/erc-4626/scan-prices.py
scripts/erc-4626/scan-vaults.py
scripts/hypersync/robustness-manual-check.py
tests/enzyme/test_price_feed.py

- Detect missing vault metadata entries and intelligently log out put missing metadata
- Needs manual clean up, add more tools and examples to manually clean up data for broken chains

Fixing issues with the vault clean up
