tradingstrategy-ai/web3-ethereum-defi

CHANGELOG.md, eth_defi/middleware.py, pyproject.toml, tests/test_middleware.py
Try to deal with
```
{'message': 'Internal JSON-RPC error.', 'code': -32603}
```
When served by a Pokt Relay.
=> Handle Pokt Network internal server errors

eth_defi/uniswap_v2/swap.py, eth_defi/uniswap_v3/swap.py
Using a fee of 0 in some tests in tradeexecutor package resulted in a confusing web3 error that was seemingly unrelated difficult to debug `(ValidationError: No valid "from" key was provided in the transaction which is required for transaction signing)`. This adds an assertion to prevent this from happening in the future.
=> Swap fee assertion

CHANGELOG.md, eth_defi/token.py, eth_defi/trade.py, eth_defi/uniswap_v2/analysis.py, eth_defi/uniswap_v3/analysis.py, eth_defi/uniswap_v3/pool.py, tests/test_token.py, tests/uniswap_v3/test_uniswap_v3_analysis.py
- Compare tokens by chain_id and address
- Make TokenDetails hashable
- Fix Uniswap v3 `analyse_by_receipt()` giving inverse price
=> Logical TokenDetails equality comparison

CHANGELOG.md, eth_defi/enzyme/erc20.py, eth_defi/enzyme/uniswap_v2.py, eth_defi/event_reader/lazy_timestamp_reader.py, eth_defi/revert_reason.py, eth_defi/tx.py, tests/enzyme/test_vault_controlled_wallet.py, tests/test_lazy_timestamp_reader.py
- Create `extract_timestamps_json_rpc_lazy` that instead of reading block timestamps upfront for the given range,
only calls JSON-RPC API when requested
- Works on the cases where sparse event data is read over long block range
=> Lazy timestamp reader

CHANGELOG.md, eth_defi/middleware.py
The nonce too low error is:
```
ValueError: {'code': -32000, 'message': 'nonce too low'}.
```
This might happen when we are broadcasting multiple transactions through multiple RPC providers using `eth_sendRawTransaction`. One provide is not yet seeing a transaction broadcast through the other provider.
=> Retry nonce too low errors

.github/workflows/test.yml, CHANGELOG.md, eth_defi/event_reader/web3factory.py, eth_defi/provider/multi_provider.py, tests/test_block_reader.py
- Allow the user to pass a custom `requests.Session` used with thread pooling by `TunedWeb3Factory`
- Switch to `ujson` for JSON-RPC decoding by default
- Fix `test_block_reader` and run it on Github CI
=> Enable session passing

CHANGELOG.md, eth_defi/hotwallet.py, eth_defi/middleware.py, eth_defi/provider/fallback.py, tests/rpc/test_fallback_provider.py, tests/test_decode_tx.py
- `eth_sendRawTransaction` was not retried correctly for `nonce too low error` with LlamaNodes due to inconsistencies in error handling  n web3.py and Ethereum nodes
=> Fix FallbackProvider to work with certain error codes

CHANGELOG.md, eth_defi/middleware.py, eth_defi/provider/ankr.py, eth_defi/provider/broken_provider.py, eth_defi/provider/fallback.py, eth_defi/token.py, tests/rpc/test_fallback_provider.py, tests/test_lazy_timestamp_reader.py, tests/test_link.py, tests/test_revert_reason.py
A special case of eth_call returning an empty result.
This happens if you call a smart contract for a block number
for which the node does not yet have data or is still processing data.
This happens often on low-quality RPC providers (Ankr)
that route your call between different nodes between subsequent calls, and those nodes
see a different state of EVM.
Down the line, not in the middleware stack, this would lead to `BadFunctionCallOutput` output. We work around this by detecting this condition in the middleware stack and triggering the middleware fall-over node switch if the condition is detected.
=> Work around BadFunctionCallOutput:  Insufficient bytes error

eth_defi/balances.py
- Ensures we read balances at a specific block height
=> Add block identifier to fetch_erc20_balances_by_token_list

CHANGELOG.md, eth_defi/confirmation.py, eth_defi/hotwallet.py, pyproject.toml, tests/provider/README.md, tests/rpc/README.md, tests/rpc/test_fallback_provider.py
- Try to abort `wait_and_broadcast_multiple_nodes`  early if we see nonce issues in the signed transactions
- Update dependencies to the latest versions
=> Nonce reuse checks

CHANGELOG.md, eth_defi/confirmation.py
- `wait_and_broadcast_multiple_nodes` will now raise the last exception if there is a failed transaction
=> Even more tx broadcast debug

CHANGELOG.md, eth_defi/uniswap_v3/swap.py, pyproject.toml
- Fix: `swap_with_slippage_protection()` clarify `max_slippage` is BPS
- API change: `swap_with_slippage_protection(max_slippage=15)` - change the default Uniswap v3
trade slippage tolerance from (unrealistic) 0.1 BPS to 15 BPS.
=> Fix BPS and percent confusion

.github/workflows/test.yml, .gitignore, CHANGELOG.md, eth_defi/trace.py, poetry.lock, pyproject.toml, scripts/debian-bullseye-compatibility/Dockerfile, scripts/debian-bullseye-compatibility/README.md, scripts/debian-bullseye-compatibility/check-install.sh, tests/rpc/test_fallback_provider.py
- Debian Bullseye and pyenv was picking up old web3-ethereum-defi version
- Create a Docker script to check installation on Debian Bullseye
- This did not then use the correct version of [safe-pysha3](https://github.com/5afe/pysha3), but picked up the old pysha3 package
- Make `pyproject.toml` to say we are compatible all they way to Python 3.12
- [pkgutil compatibility fixes](https://stackoverflow.com/questions/77364550/attributeerror-module-pkgutil-has-no-attribute-impimporter-did-you-mean).
- [Upgrade to Pandas 2.x](https://github.com/pandas-dev/pandas/issues/53665), needed for Python 3.12 compatibility
- Upgrade to the latest Web3.py 6.x version
- Python 3.12 changes `ast` module and this has breaking changes with `eth_trace` library. Workaround them.
- Disable …
=> Python 3.11, 3.12 and Debian Bullseye compatibility

docs/source/api/one_delta/index.rst, eth_defi/one_delta/lending.py, eth_defi/one_delta/position.py, tests/one_delta/test_one_delta_lending.py, tests/one_delta/test_one_delta_short_single_pair.py
Proxy functions to interact with Aave:
- Supply collateral
- Withdraw collateral
Part of https://github.com/tradingstrategy-ai/trade-executor/issues/678
=> 1delta proxy functions for Aave

CHANGELOG.md, eth_defi/enzyme/deployment.py, eth_defi/enzyme/generic_adapter_vault.py, eth_defi/enzyme/policy.py, tests/enzyme/test_enzyme_policy.py
- Enable configuration for `sharesActionTimelock`, which will prevent shares price arbitrage attacks
- However not enabled by default, as it also breaks our deposit contract that calls `buySharesOnBehalf` which needs to have the deposit contract whitelisted by Enzyme FundDeployer
```solidity
/// @dev This function is freely callable if there is no sharesActionTimelock set, but it is
/// limited to a list of trusted callers otherwise, in order to prevent a griefing attack
/// where the caller buys shares for a _buyer, thereby resetting their lastSharesBought value.
function buySharesOnBehalf(
address _buyer,
uint256 _investmentAmount,
uint256 _minSharesQuantity
) external returns (uint256 sharesReceived_) {
bool hasSharesActionTimelock = getSharesActionTimelock() > 0;
address …
```
=> Enzyme redemption time lock

eth_defi/middleware.py
Add `ValueError: {'code': -32000, 'message': 'execution aborted (timeout = 5s)'}` to be retryable in multiprovider
=> Add another retryable error message

docs/source/tutorials/make-uniswap-v3-swap-in-python.rst, eth_defi/confirmation.py, eth_defi/uniswap_v3/swap.py, scripts/make-swap-on-uniswap-v3.py
- Add a tutorial how to perform a Uniswap v3 swap in Python
=> Uniswap v3 swap tutorial

contracts/in-house/src/GuardedGenericAdapter.sol, eth_defi/enzyme/generic_adapter_vault.py, eth_defi/enzyme/policy.py, eth_defi/enzyme/vault.py, eth_defi/trace.py, tests/enzyme/test_guard_enzyme_uniswap_v2.py
- Move `deploy_guard()` to its own function and refactor Enzyme vault deployment to more manageable
=> Split deploy guard

poetry.lock, pyproject.toml
- Pinning Pandas >2 was too new, and breaks some older library combos as they only work with Pandas 1.5.2
=> Pandas pin down update

CHANGELOG.md, eth_defi/token_analysis/tokensniffer.py, pyproject.toml
- Add: Custom cache interface support for `CachedTokenSniffer()`
=> TokenSniffer custom cache

eth_defi/confirmation.py, scripts/enzyme/fetch-supported-tokens-arbitrum.py
- Make sure MEV blocker is only provider receiving send_raw_transaction
=> If any of MEV blocking providers are enabled, do not attempt to broadcast through other providers

.github/workflows/test.yml, CHANGELOG.md, docs/source/api/index.rst, docs/source/api/lagoon/index.rst, docs/source/api/safe/index.rst, docs/source/api/velvet/index.rst, eth_defi/lagoon/safe_compat.py, eth_defi/lagoon/vault.py, eth_defi/safe/__init__.py, eth_defi/safe/safe_compat.py, eth_defi/safe/trace.py, eth_defi/uniswap_v2/constants.py, poetry.lock, pyproject.toml, tests/lagoon/conftest.py, tests/lagoon/test_lagoon_info.py, tests/lagoon/test_lagoon_swap.py
- Integrate safe-eth-py library, so we do not need to copy-paste all Safe integration Python code
- Fetch Safe core metadata, for Lagoon vault info
- Perform a swap using wildcard access module in the Lagoon test setup
=> Lagoon vault integration

eth_defi/hotwallet.py, eth_defi/lagoon/deployment.py, eth_defi/safe/deployment.py, tests/lagoon/conftest.py, tests/lagoon/test_deploy_base.py
- Forge and Gnosis Safe lib make signing transactions correctly very painful
=> Work around nonce sync issues in Lagoon deployment

eth_defi/aave_v3/reserve.py
The config for the Sepolia test net contracts was missing.
This commit now allows me to test my scripts on Sepolia before deploying my contracts and scripts to mainnet
=> Adding Sepolia V3 config to AAVE v3

.github/workflows/test.yml, CHANGELOG.md, docs/source/api/data_research/index.rst, docs/source/api/vault/index.rst, eth_defi/erc_4626/vault.py, eth_defi/research/vault_metrics.py, eth_defi/research/wrangle_vault_prices.py, eth_defi/token_analysis/tokensniffer.py, eth_defi/vault/base.py, eth_defi/vault/vaultdb.py, eth_defi/vault/wrangle.py, poetry.lock, pyproject.toml, scripts/erc-4626/clean-prices.py, scripts/erc-4626/scan-prices.py, tests/enzyme/test_enzyme_deploy.py, tests/guard/test_guard_simple_vault_aave_v3.py, tests/guard/test_guard_simple_vault_erc_4626.py, tests/rpc/test_mev_blocker.py
- Clean 1h vault price data 
- Unlike in previous iterations, do data cleaning as the post operation for scanning: we have so much data that cleaning data on every notebook run is not feasible
- Move a lot of vault analysis functionality to their own Python modules, instead of copy-pasting in notebook to improve documentation and reusability
=> New vault data cleaner
